spring.application.name=

api.security.token.expiration=
api.security.token.secret=

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=
spring.jpa.hibernate.ddl-auto=
spring.jpa.database-platform=
spring.jpa.show-sql=
spring.jpa.properties.hibernate.format_sql=
spring.jpa.properties.hibernate.highlight_sql=
#spring.flyway.enabled=
#spring.flyway.baseline-on-migrate=